name: Bundles Update

on:
  push:
    paths:
      - 'assets/bundles/**'
  workflow_dispatch:

jobs:
  runPush:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Update bundles
        run: |
          ./gradlew updateBundles
          
          if [ -n "$(git status --porcelain assets/bundles/)" ]; then
            git config --global user.name "Github Actions"
            git config --global user.email "actions@github.com"
            git add assets/bundles/*
            git commit -m "Automatic bundle update"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Sync bundles
        run: |
          git clone https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/WMF-Industries/gamemode-translations.git gamemode-translations
          cp -R assets/bundles/* gamemode-translations/FloodCompat/
          cd gamemode-translations
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "Github Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Sync bundles from FloodCompat [skip ci]"
            git push
          fi